xah-fly-keys.el
Added support for workman layout.
But I'm ashamed to admit I have copied the function `xah--dvorak-to-workman` from `xah--dvorak-to-qwerty` after I failed to use higher order function to avoid the duplication. I'm more than happy to fix that if you may shed me some light on the improvement!
=> Added support for workman layout

xah-fly-keys.el
My keyboard doesn't have an F22 key, and my guess is that the binding was supposed to parallel the one two lines above.
=> fix what looks like a typo

xah-fly-keys.el
The Brazilian keyboard is mostly similar to qwerty, the only relevant changes are the keys 'ç', ';' and '~' replacing ';', '/' and '\''.
=> Support for Brazilian ABNT keyboard

xah-fly-keys.el
Change behavior of xah-reformat-lines to use the buffer's current value of fill-column by default, like xah-fill-or-unfill.
(also touch-up that function's docstring)
This seems best to me, but, of course, do close if you disagree :)
=> make xah-reformat-lines use fill-column by default

xah-fly-keys.el
Just a few readability edits to the comment lines around `xah-fly--tab-key-map`.
=> edit comments for xah-fly--tab-key-map

xah-fly-keys.el
Setting these variables to nil in the library file itself requires the user to reset them after every update.
=> document disabling Control and Meta keyboard shortcuts

xah-fly-keys.el
Changes:
- Added azerty keymaps for both France and Belgium.
- Renamed 'programer-dvorak' to 'programmer-dvorak'
- Replaced the code duplication in `xah--dvorak-to-...` by a macro, which is also able to translate shortcuts with a single modifier. To make this work `kbd` has to be applied after `xah-fly--key-char`. I only added this to the C-'number' shortcuts as the other shortcuts of this type are standard ones.
- Fixed bug where "a" was always assigned to `'execute-extended-command` even if the keymap changes "a".
=> Added azerty support, and some other small changes

xah-fly-keys.el
https://github.com/xahlee/xah-fly-keys/issues/64
I've commented out your mutable xah-fly-key-map. Instead, I  am switching between two immutable keymaps: xah-fly-manage-insert-mode-map and xah-fly-manage-command-mode-map. Note my use of emulation-mode-map-alists. 
Also, there is reformatting. I have a doubt about that, and at least it might be better to do it  as a separate commit. It's better to see at a glance which commits are just reformatting and which actually change code. But even more than that, I don't think I have an argument to make for bulk-reformatting tools at all.  If you care about code review and bug tracking, it can really mess with your process. I'm not actually hung up on code style. Except I do have one point -- why do I have to reformat everything all at the same …
=> Refactoring to use multiple minor-mode keymaps

xah-fly-keys.el
Hey Xah,
Saw your notes in your blog and think I figured out why the recursive-load was happening: because of the way the Customize interface works, it tries to use the setter (same as the `custom-set` property) to set the default value. However, the setter is `xah-fly-keys-set-layout`, which reloads the file to update the keybindings to the new layout. Loading the file again calls the setter again which reloads the file, etc which causes the recursive load.
I've fixed this by not making the Customize interface dependent on `xah-fly-keys-set-layout` and only have it reload the file if it was already loaded and the new value is different than the old one. Otherwise, the bindings will not be updated to use the new layout when people set the layout through Customize. (Also removed the extra …
=> Permanent recursive-load fix

xah-fly-keys.el
In the discord dxlr8r was expecting the binding he made before enabling xfk to be available in both insert and command modes, which seems like the intuitive behavior, so I've updated the code to put such bindings in the shared map
=> Put bindings made before xfk is enabled in shared map

xah-fly-keys.el
Realized I had forgotten to add back the meta key using the new
`xah-fly--define-keys`; added it back now
=> Re-add M-SPC binding

README.md, xah-fly-keys.el
Thanks for xah-fly-keys, this PR is basically my first attempt to walk (work) with your keybindings.
There are many keyboard layouts specifically optimized for the German language.
This PR adds support for the 3 that are probably most used.
They are all pretty similar in that they all share the same 6 levels but have a different arrangement of the letters on level 1.
Unfortunately they all rebind CAPS-lock to enter the 4th level so xah-fly-keys can only be used with the "M-SPC" fallback.
There are English resources only for the oldest of them: [neo 2](https://en.wikipedia.org/wiki/Neo_(keyboard_layout))
While this website provides detailed statistical information for the others it is all in German, so I'll link only the [picture gallery](http://adnw.de/index.php?n=Main.Grafiksammlung)
=> Add support for keyboard layouts: neo2, koy & adnw

README.md, xah-fly-keys.el
The colemak mod dh files from [colemakmods](https://github.com/ColemakMods/mod-dh) have switched over to a version with m on the home row. I have added support for this layout, with the name "mod-dh-new". The pr uses the version where the iso key is used for the letter z, although that doesn't affect keys which xah-fly-keys uses.
=> Support for newer mod dh with m on the home row

xah-fly-keys.el
When looking for a way to make `xah-select-line` work with visual lines, I found that there's no `forward-visual-line`; instead, I discovered that `end-of-visual-line` can take an optional parameter. The default behavior equals `(end-of-visual-line 1)`, but when you pass `2`, it goes to the end of the _next_ visual line.
Then I found that it was odd that the key binding does always go down 1 line first when a region is active, even if point is in the middle of a line.K  Instead, I wanted to go to the end of the line first, even with a region active, and *then* advance to the next line. I added a new branching path for that.
I left the old code untouched; but if you like that behavior, I can extend the non-visual variant to go to end-of-line first, and if it's already there, advance to the …
=> Support visual-line-mode in xah-select-line

xah-fly-keys.el
To be honest, I don't know if this kind of integration with other packages should be part of XFK, or rather part of the user's `init.el`. It probably doesn't scale to try to support the 'arrow keys' in the XFK command map everywhere. 
Just close the PR if you htink XFK shouldn't support that.
I split this into multiple commits in case you want to keep parts of this and want me to revert e.g. the docstring changes, or keep the docstring change and rash the indent-rigidly key mapping.
=> indent-rigidly: support XFK arrow keys

xah-fly-keys.el
It looks like this was removed in: 3ff7e5d561dcb37678f1c7bdfbd49bf49debb98c
but this was left in.
=> Remove `remove-hook' that no longer applies

xah-fly-keys.el
To give users the ability to change "c" and "i" to something different. 
I found the `doom-modeline` colored mode bullets more useful to see the currently active mode, maybe because the characters are rather small (with my config).
Users can now customize the indicators including whitespace like so (random example):
(setq xah-fly-insert-mode-indicator "● ")
(setq xah-fly-command-mode-indicator "– ")
=> Add -indicator variables to customize the mode line

xah-fly-keys.el
Matches `shell' behavior.
Also how come "[\t\n ]" was removed[1]?  In `diff-mode' they insert a space at
the start of lines and currently it just skips to the top.
[1] https://github.com/xahlee/xah-fly-keys/commit/b8414bed05e7f0f74cb55fd6ba56978f973d1414
=> `xah-beginning-of-line-or-block': Eshell go to start of input

xah-fly-keys.el
`xah-fly-command-mode-init` uses a feature of the `set-transient-map`
that explicitly disables a clean up on a pre-command-hook
invocation (`keep-pred` parameter):
```
(setq xah-fly--deactivate-command-mode-func
(set-transient-map xah-fly-command-map (lambda () t)))
```
In our case it is `(lambda () t)`.
From the code of the `set-transient-map`:
```
However, if the optional argument KEEP-PRED is t, MAP stays
active if a key from MAP is used.  KEEP-PRED can also be a
function of no arguments: it is called from `pre-command-hook' and
if it returns non-nil, then MAP stays active.
```
Although `xah-fly-command-map` map stays active until insert mode is
started (as it should be since we don't want quite a command mode
prematurely) and XFK takes responsibility of invoking the cleanup
function …
=> make sure to clean up on xah-fly-command-mode-init subsequent calls

xah-fly-keys.el
Don't skip over tabs/spaces, when they are the only things on that line.
This shows why I think it should be like this.  Have your cursor under "Fifth line." and run `xah-beginning-of-line-or-block'.  The cursor will now move under "First line.", skipping all the lines in between.
```
First line.
Second line.
Third line.
Forth line.
Fifth line.
```
=> `xah-beginning-of-line-or-block': tabs/spaces

xah-fly-keys.el
The linux branch of xah-open-in-external-app and xah-show-in-desktop that uses
xdg-open starts another child process to open its parameters with the
appropriate command then it quits however it makes emacs kill the subprocess as
soon as xdg-open has finished therefore the files opened externally are also
instantaneously killed.
=> fix xdg-open quits too early and kill external app

xah-fly-keys.el
Add the standard Swedish QWERTY layout as 'qwerty-se'.
=> Add qwerty-se (Swedish) layout

xah-fly-keys.el
- Fix the bug where brackets with prefix characters would not be properly
deleted (solves #167 )
- Add optional parameter DeletePrefix to the following functions:
xah-delete-backward-bracket-text
xah-delete-backward-bracket-pair
xah-delete-bracket-text-backward
. 
If DeletePrefix is non-nil, also delete any prefix characters before the opening bracket.
It is currently not passed, so the default behavior remains the same.
- Fix the bug where xah-smart-delete fails to delete an unbalanced bracket.
xah-delete-bracket-text-backward now deletes any unmatched brackets before point
instead of giving an error message
- Add the ability to dispatch xah-smart-delete default behavior by setting
xah-smart-delete-dispatch:
.
If the Alist contains a value pair of the form
(default . ‹function-name›) …
=> xah-smart-delete related fixes and improved customization

xah-fly-keys.el
Here's my suggestion for solving the open problem in the Neo2 layout. The solution accurately reproduces the Neo2 characters.
For your information: In the Neo2 layout, dead keys like ^, `, or ´ are generated by pressing the dead key and the space bar. Not by pressing them once. So, is it better to use a character from the third layer? I don't have an answer yet.
=> Fix for neo2 layout.
